In [1]:
import numpy as np

In [10]:
data = np.loadtxt("C:\\Users\\DELL\Downloads\\survey.txt", dtype='int')
data

array([ 7, 10,  5, ...,  5,  9, 10])

In [3]:
data.ndim

1

In [4]:
data.size

1167

In [5]:
data.shape

(1167,)

# 9 and 10 are promotors

In [7]:
data >= 9

array([False,  True, False, ..., False,  True,  True])

In [12]:
Promotors = data[data>=9]
Promotors

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [13]:
Promotors.size

609

In [14]:
Promotors.shape

(609,)

In [15]:
Promotors[0]

10

In [17]:
(data==9) | (data == 10)

array([False,  True, False, ..., False,  True,  True])

In [21]:
data[(data==9) | (data == 10)].size

609

In [22]:
data[data>=9].size

609

In [24]:
Passive = data[(data==7) | (data==8)]
Passive

array([7, 7, 7, 7, 8, 8, 8, 7, 7, 7, 8, 8, 7, 8, 8, 8, 8, 7, 7, 7, 8, 7,
       7, 7, 8, 7, 8, 8, 7, 8, 8, 8, 7, 8, 7, 8, 8, 7, 8, 7, 8, 7, 7, 8,
       8, 8, 7, 7, 8, 8, 8, 7, 7, 7, 8, 7, 7, 8, 7, 7, 7, 8, 7, 7, 8, 8,
       8, 7, 7, 7, 7, 7, 8, 8, 7, 8, 7, 8, 8, 7, 8, 7, 7, 8, 7, 7, 7, 7,
       7, 8, 8, 7, 7, 8, 8, 8, 8, 8, 7, 7, 7, 8, 7, 8, 8, 7, 7, 8, 8, 7,
       7, 8, 7, 7, 8, 8, 8, 7, 7, 8, 8, 8, 8, 7, 7, 7, 8, 7, 7, 7, 7, 8,
       7, 8, 7, 7, 7, 8, 8, 8, 7, 8, 8, 8, 8, 7, 8, 7, 7, 7, 7, 7, 8, 7,
       7, 7, 7, 8, 7, 8, 8, 7, 7, 8, 8, 7, 8, 8, 7, 7, 7, 8, 8, 7, 7, 8,
       7, 7, 7, 8, 7, 7, 7, 8, 7, 7, 7, 7, 7, 8, 8, 7, 8, 7, 7, 7, 8, 8,
       8, 8, 8, 7, 8, 7, 7, 8, 7, 7, 8, 7, 8, 8, 7, 7, 8, 8, 8, 7, 8, 8,
       7, 7, 7, 7, 7, 8])

In [25]:
Passive.size

226

In [26]:
Passive.shape

(226,)

In [27]:
Detractors = data[data<=6]
Detractors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [28]:
Detractors.size

332

In [29]:
Detractors.shape

(332,)

In [30]:
Promotors = Promotors.size
Promotors

609

In [31]:
Passive = Passive.size
Passive

226

In [32]:
Detractors = Detractors.size
Detractors

332

In [33]:
data.size

1167

In [34]:
Promotors+Passive+Detractors

1167

In [36]:
NPS = 100*(Promotors - Detractors)/data.size
NPS

23.736075407026565

In [37]:
np.round(NPS,2)

23.74

In [3]:
data[:5]

array([ 7, 10,  5,  9,  9])

In [4]:
data.shape[0]

1167

In [8]:
arr = np.empty(data.shape, dtype='U20')
arr

array(['', '', '', ..., '', '', ''], dtype='<U20')

In [11]:
arr[data>=9] = 'Promotors'
arr

array(['Promotors', 'Promotors', 'Promotors', ..., 'Promotors',
       'Promotors', 'Promotors'], dtype='<U20')

In [15]:
arr[(data==7) | (data==8)] = 'Passive'
arr

array(['Passive', 'Promotors', 'Promotors', ..., 'Promotors', 'Promotors',
       'Promotors'], dtype='<U20')

In [16]:
arr[data <= 6] = 'Detractor'
arr[:20]

array(['Passive', 'Promotors', 'Detractor', 'Promotors', 'Promotors',
       'Detractor', 'Passive', 'Promotors', 'Promotors', 'Promotors',
       'Promotors', 'Detractor', 'Promotors', 'Promotors', 'Passive',
       'Promotors', 'Detractor', 'Promotors', 'Passive', 'Promotors'],
      dtype='<U20')

In [17]:
arr.size

1167

In [21]:
arr[arr == 'Passive'].size

226

In [22]:
arr[arr == 'Detractor'].size

332

In [23]:
arr[arr == 'Promotors'].size

609

In [24]:
226+332+609

1167